<h3> Basic R Lang Assignments </h3>
<h4> Variable Assignment </h4>

In [1]:
#left ward assignment in R
comp_num <- 3+1i
class(comp_num)

#right ward assignment
"R Lang"-> ch
class(ch)

[1] "complex"

[1] "character"

In [2]:
# QUE 1:
# CREATE DIFFERENT VARIABLES FOR EACH DATATYPE AND ASSIGN (STORE) VALUES TO EACH. 
# LIKE NUMERIC VARIABLE, CHAR VARIABLE, COMPLEX VARIABLE, INTEGER VARIABLE, VECTOR VARIABLE, LIST VARIABLE
# ALSO PRINT ITS class() and typeof() for all variables
# hint: datatypes: **i, **L, 'char', ***.**, boolean (true/false)

#ANSWER TYPE FROM HERE
x=10
x
typeof(x)
class(x)

y=12.5
y
typeof(y)
class(y)

z=12.5L
z
typeof(z)
class(z)

a=12L
a
typeof(a)
class(a)

b="100"
typeof(b)
class(b)

c=30i
c
typeof(c)
class(c)

d=c(1,2,5,8,6)
d
typeof(d)
class(d)


x=15
x>=9 & x>=18
x>9 & x<16
x>=9 & x<=16

x=c(1,2,3,3.5)
is.vector(x)
x=c(50,32,36.5,"b")
typeof(x)
class(x)
x=c(25,"B",25L)
is.vector(x)
typeof(x)
class(x)
x=c(2,31,"b")
is.vector(x)
typeof(x)
class(x)
as.vector(x)

x=c(1,2,3,5)
y=c("abc","xyz","pqr")
z=c(1.2,3.5,6.8)
list(x,y,z)
list1=list(x,y,z)
list1
typeof(list1)
class(list1)





[1] 10

[1] "double"

[1] "numeric"

[1] 12.5

[1] "double"

[1] "numeric"

[1] 12.5

[1] "double"

[1] "numeric"

[1] 12

[1] "integer"

[1] "integer"

[1] "character"

[1] "character"

[1] 0+30i

[1] "complex"

[1] "complex"

[1] 1 2 5 8 6

[1] "double"

[1] "numeric"

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

[1] "character"

[1] "character"

[1] TRUE

[1] "character"

[1] "character"

[1] TRUE

[1] "character"

[1] "character"

[1] "2"  "31" "b"

[[1]]
[1] 1 2 3 5

[[2]]
[1] "abc" "xyz" "pqr"

[[3]]
[1] 1.2 3.5 6.8

[[1]]
[1] 1 2 3 5

[[2]]
[1] "abc" "xyz" "pqr"

[[3]]
[1] 1.2 3.5 6.8

[1] "list"

[1] "list"

In [3]:
a_ <- FALSE
print(a_)

# CHECK HOW ASSIGN WORKS? 
assign("a",10)
print(a)
print(typeof(a))

# QUE. 2:
# ASSIGN ALL DATA TYPE VALUES TO below VARIABLES USING assign() FUNCTION AND 
# PRINT ITS VALUES AND TYPE USING typeof() like above example
# VARIABLE NAMES: numeric_var, chr_var, int_var, cmplx_var, bool_var 

# WRITE ANS FROM HERE
chr=52.2
chr=25
chr

smart=100
smart=522
smart


digits<-100
digits





[1] FALSE
[1] 10
[1] "double"


[1] 25

[1] 522

[1] 100

In [4]:
# ASSIGNMENT OPERATORS 
# USED TO ASSIGN VALUES TO VARIABLES, BELOW ARE THE SOME EXAMPLES FOR REFERENCE

#Assignment Operator
num1 <- 5  # left ward assignment
num1 <<- 10 
num1

15 -> num2 # right ward assignment
20 ->> num2
num2

# using "=" operator you can assign value also
var = 10
var

[1] 10

[1] 20

[1] 10

<h4> Booleans / Comparisons: </h4>


In [5]:
#Logical Values
#  COMPARING VALUES USING COMPARISON OPERATORS
print("Comparison with only values:")
13 < 3
12 == 12
12 != 10
20 > 19

print("Comparison using variables: ")
#using variables to compare values 
x <- 20 # assigned 20 to x
y <- 10 # assigned 10 to y
x < y  # checking x is less than y
x > y # checking x is greater than y
x == y # checking x is equal to y

[1] "Comparison with only values:"


[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

[1] "Comparison using variables: "


[1] FALSE

[1] TRUE

[1] FALSE

In [6]:
# QUE 3.
# COMPARE DIFFERENT TYPE OF VALUES USING  OPERATORS LIKE " >, <,==, <=, >=, <>"
# TRY TO COMPARE DIFFERENT DATATYPES LIKE char, integer, numeric, boolean
# hint: above given example

# WRITE ANSWER BELOW :
15<20
12<5
12==11
90!=100
100>101

x=23
y=20
x>y
x<y
x==y
x!=y


[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

<h4> String Manupulations: </h4>

In [7]:
##STRING 

#create a string
'Hello, R'

#assign a string to a var
new_str <- "Hello World"
print(new_str)

#create multiple line string
multi_str <- "My name is Dipali
my age is 25
my gender is female."
cat(multi_str)

#length of string
nchar(new_str)

#logical check of string/character in the given string
grepl("a", new_str)
grepl("H", new_str)

#integer check of string/character in the given string
grep("a", new_str)
grep("she", new_str)

#string concatenation
str1 <- 'Dipali'
str2 <- "Pooja"
paste(str1, str2)

#escape characters in string
s <- "R \"Programming\" Language"
cat(s)
str <- "Hi\n\\my name is Dipali\n \bI'm R Programmer."
cat(str)

[1] "Hello, R"

[1] "Hello World"
My name is Dipali
my age is 25
my gender is female.

[1] 11

[1] FALSE

[1] TRUE

integer(0)

integer(0)

[1] "Dipali Pooja"

R "Programming" LanguageHi
\my name is Dipali
 I'm R Programmer.

In [8]:
# QUE 4.
# USE ABOVE ALL FUNCTIONS and BELOW GIVEN LIST OF FUNCTIONS ON DIFFERENT TYPE OF DATA WHICH YOU LIKE. 
# UNDERSTAND PURPOSE OF EACH FUNCTION AND PERFORM DIFFERENT COMBINATIONS.
# grep()
# nchar()
# paste()
# sprintf()
# substr()
# strsplit()
# regex()
# gregexpr()

# REFERENCE WEBSITE FOR EXAMPLES OF ABOVE FUNCTIONS : https://data-flair.training/blogs/r-string-manipulation/ 

# WRITE ANSWER FROM HERE.
x=c(1,2,3,120,12,12L)
x
length(12L)
nchar(x)
grepl("bye",x)
grep(12L,x)
x="nawaz"
y="siddiqui"
paste(x,y)
sprintf(x)
substr(x,2,3)
strsplit(x,2,3)
strsplit(y,"i","u")







[1]   1   2   3 120  12  12

[1] 1

[1] 1 1 1 3 2 2

[1] FALSE FALSE FALSE FALSE FALSE FALSE

[1] 4 5 6

[1] "nawaz siddiqui"

[1] "nawaz"

[1] "aw"

[[1]]
[1] "nawaz"

[[1]]
[1] "s"  "dd" "qu"

In [9]:
x="xyz1 23abc"
strsplit(x,2,3)
strsplit(x,"y")
strsplit(x,"")

[[1]]
[1] "xyz1 " "3abc"

[[1]]
[1] "x"        "z1 23abc"

[[1]]
 [1] "x" "y" "z" "1" " " "2" "3" "a" "b" "c"

<h4> ARRAYS: </h4>

In [10]:
#Array

#1D array
one_dim <- array(c(1:10))
one_dim

#2D array
two_dim = array(one_dim, dim=c(2, 3, 2))
two_dim

#access items
new1 = array(c(1,2,3,4),dim=c(2,2))
new1
new1[1,2]
new1[2,2]
new1[,c(1)]
new1[c(1),]

#check the existence of element/item
1 %in% new1
5 %in% new1
3 %in% new1

#number of row & col
dim(new1)
dim(two_dim)
dim(one_dim)

#length of array
length(new1)
length(one_dim)
length(two_dim)

[1]  1  2  3  4  5  6  7  8  9 10

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9    1
[2,]    8   10    2

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[1] 3

[1] 4

[1] 1 2

[1] 1 3

[1] TRUE

[1] FALSE

[1] TRUE

[1] 2 2

[1] 2 3 2

[1] 10

[1] 4

[1] 10

[1] 12

In [11]:
# QUE. 5:
# CREATE ONE DIMENSIONAL ARRAYS FOR NUMERIC, CHR, BOOLEAN, INTEGER DATATYPES 
# ASSIGN IT TO RESPECTIVE VARIABLES

# WRITE ANSWER FROM HERE.

int_array = array() # integer values array
print(int_array)

chr_array = array() # chr values array
print(chr_array)

bool_array = array() # array of TRUE, FALSE 
print(bool_array)

[1] NA
[1] NA
[1] NA


In [12]:
#  QUE. 6:
# CREATE TWO DIMENSIONAL ARRARY FOR NUMERIC AND CHR DATATYPES 
# FOLLOW STEPS GIVEN ABOVE OR SEARCH ON GOOGLE FOR "TWO DIMENSIONAL ARRAY IN R"

# hint: https://www.geeksforgeeks.org/multidimensional-array-in-r/

# WRITE FROM CODE HERE

chr_arr = array() # create here chr 2 dimensional array
print(chr_arr)

num_arr = array() # create here numerix 2 dimensional array
print(num_arr)


[1] NA
[1] NA


In [13]:
# QUE. 7:
# TRY TO CREATE MULTI DIMENSIONAL ARRAY FOR NUMERIC DATA TYPE. 

# hint: https://www.geeksforgeeks.org/multidimensional-array-in-r/

# WRITE CODE FROM HERE

